# ~/.local/share/intake/catalog.yml
sources:
  mongo:
    driver: bluesky-mongo-normalized-catalog
    args:
      metadatastore_db: mongodb://mongo:27017/metadatastore
      asset_registry_db: mongodb://mongo:27017/asset_registry
